[keys.normal]
"C-r" = [":write", ":sh kitty @ send-text --match cmdline:python '%%run \"%{buffer_name}\"\n'"]
"C-a" = [":write", ":sh python .state_manager.py \"%{buffer_name}\"", "select_all", "delete_selection"]
