[keys.normal]
"C-r" = [":write", ":sh kitty @ send-text --match cmdline:python 'prun(\"%{buffer_name}\")\n'"]
"C-a" = [":write", ":sh kitty @ send-text --match cmdline:python 'new_cell(\"%{buffer_name}\")\n'", "select_all", "delete_selection"]
